### ISSUE TITLE
Dependency of TranslationDumper on BazingaJs route

### ISSUE THREAD

**Issue by monteiro** [willdurand/BazingaJsTranslationBundle#190]
When  I remove the route the dumper does not work. Maybe I just want to fetch the static translation file and not use the controller.

Goal: Investigate if we can remove this route dependency. 

```
Installing translation files in web/js directory
PHP Fatal error:  Call to a member function getRequirements() on null in /var/snap-ci/repo/sah-build/vendor/willdurand/js-translation-bundle/Bazinga/Bundle/JsTranslationBundle/Dumper/TranslationDumper.php on line 125

Fatal error: Call to a member function getRequirements() on null in /var/snap-ci/repo/sah-build/vendor/willdurand/js-translation-bundle/Bazinga/Bundle/JsTranslationBundle/Dumper/TranslationDumper.php on line 125

                                                              
  [Symfony\Component\Debug\Exception\FatalErrorException]     
  Error: Call to a member function getRequirements() on null  
                                                              

bazinga:js-translation:dump [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--] <command> [<target>]
```

**Comment by stof** [comment]
The route is used for 2 things:

- getting the list of supported formats (from the requirements)
- getting the path, to dump the file as a drop-in replacement.

Here is my proposal:

- hardcode the list of supported formats in the dumper (it does not change that often, we have not added anything other than ``js`` and ``json`` since years)
- change the dumper signature to take a pattern as argument instead of getting it from the Route object, and handle this in the command. The command could then have an option to pass a pattern for the file (and the route be used as a fallback only when the option is not provided)
