### ISSUE TITLE
Generated uri for translations route should be relative and not absolute

### ISSUE THREAD

**Issue by cedricjacquet** [willdurand/BazingaJsTranslationBundle#250]
<script src="{{ url('bazinga_jstranslation_js') }}"></script>
Generate an uri like this http://test.domain.com/translations or https://test.domain.com/translations based on configuration.

It's an issue when you have an apache configured in http with a reverse proxy in https in front of him.
The route generates http://test.domain.com/translations but the client call https://test.domain.com

This generate mixed content and the content is simply discard.
Why not only generate a relative uri /translations ?

**Comment by stof** [comment]
Well, if you configure trusted proxies properly in Symfony, Symfony will now that the site is being accessed through HTTPS and will generate the right URL.

And if you want a relative URL, it is also possible. Use `path('bazinga_jstranslation_js')` instead of `url('bazinga_jstranslation_js')`. There is nothing specific to this bundle here. Both `path()` and `url()` are provided by Symfony itself. And this URL generation happens in your own code.

**Comment by cedricjacquet** [comment]
Perfect ! thanks a lot
