### ISSUE TITLE
getTranslations.js.twig improvement?

### ISSUE THREAD

**Issue by wumke** [willdurand/BazingaJsTranslationBundle#281]
There is a lot of repeated code and constants in the generated js files, so I've tried top optimize it a bit:

```
(function (t) {
{% if include_config %}
t.fallback = '{{ fallback }}';
t.defaultDomain = '{{ defaultDomain }}';
{% endif %}
{% for locale, domains in translations %}
{% for domain, messages in domains %}
var {{ domain }}_{{ locale }} = {
{% for key, message in messages %}{{ key|json_encode|raw }}:{{ message|json_encode|raw }}{% if not loop.last %},{% endif %}{% endfor %}
};
for (var key in {{ domain }}_{{ locale }}) {
t.add(key, {{ domain }}_{{ locale }}[key], "{{ domain }}", "{{ locale }}");
}
{% endfor %}
{% endfor %}
})(Translator);
```

old output:
```
(function (t) {
// en
t.add("key1", "val1", "javascript", "en");
t.add("key2, "val2", "javascript", "en");
})(Translator);
```

New output:
```
(function (t) {
// en
var javascript_en = {
"key1":"val1","key2":"val2"};
for (var key in javascript_en) {
t.add(key, javascript_en[key], "javascript", "en");
}
})(Translator);
```

Results in my app with 175 translation pairs: from 18.435KB to 13.469KB = +-25% savings!

Does anyone know a reason why not to implement it this way?

**Comment by stof** [comment]
please check the savings after gzip being applied. To me, the difference will be very small, as that's precisely the kind of things that gzip is best at optimizing.

Btw, your code is missing lots of things:

- iteration with `for (var key in javascript_en) {` is subject to prototype changes. You need to add `hasOwnProperty` checks to be safe (and we don't know what other JS will be loaded alongside this bundle, so we **must** play safety
- there is nothing guaranteeing that a domain can be used to build a JS identifier to name a variable. *Any* string can be used there (well, due to Symfony loading translations from files by default, it might be hard to use some chars, but you can also have custom loaders anyway). The locale is a bit safer to use. To be safe, you would need to generate valid variable names all the time, which will add complexity (and we should still make them deterministic names, to avoid breaking caching)
- this now forces the browser to instantiate a big JS object (well, several ones if you have multiple domains or locales), that will be used only to iterate over it. That might be bad for performance (but to be checked)

**Comment by wumke** [comment]
- I know one should check 'hasOwnProperty', but this was just a quick and dirty idea and test :-)
- Gzipped 3570 to 3490 = only +-2% at my translation set. So that's not that much. 
- No idea about js performance... (or gzip compression performance)

I use the json output now (easiest option imho when using webpack and not wanting to have a global Translator var).
Guess what: Json output has about the same size as the optimized js version.

I'll close this one... 
(Anyway, thanks for the quick reply, and have a nice weekend!)
