### ISSUE TITLE
Cache translations

### ISSUE THREAD

**Issue by grekpg** [willdurand/BazingaJsTranslationBundle#297]
Hi . 
Is posible to enable cache for translations 

_bazinga_jstranslation:
  resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

give my 
Accept-Ranges: bytes
Age: 0
Cache-Control: max-age=0, must-revalidate, private
Connection: keep-alive

can You add parameter for controller for setup cache ?

**Comment by stof** [comment]
Actually, the cache is *already* configured: https://github.com/willdurand/BazingaJsTranslationBundle/blob/43a51cf1fa2adc4c7bb985af8c9ebc414eea04a0/Controller/Controller.php#L186-L189

I suspect that your security firewall covers the URL loading translations, and so Symfony forces it to use a private cache due to using the session.
The default security configuration has a rule which excludes some prefixes from security firewalls: https://github.com/symfony/recipes/blob/3a9b46f8fbf2810a15ba9f1694064f7ad612883c/symfony/security-bundle/5.1/config/packages/security.yaml#L6-L8
If you load the bundle routes with a `/js` prefix, that pattern will work out of the box. If you load them without a prefix (as show in the readme), you should add `translations` to the list of prefixes in that config (and if you load them with your own prefix, use that prefix in the config) to ensure that the security system does not run on the loading of translations.

**Comment by monteiro** [comment]
Thanks @stof !
