### ISSUE TITLE
The dependancy IntlMessageFormat was not found in ./node_modules/bazinga-translator/js/translator.js

### ISSUE THREAD

**Issue by ChiMei-L** [willdurand/BazingaJsTranslationBundle#303]
Hello,

I got an error when I try to import Translator from 'bazinga-translator'
```
This dependency was not found:

* IntlMessageFormat in ./node_modules/bazinga-translator/js/translator.js

To install it, you can run: npm install --save IntlMessageFormat
```

Here are the steps that I did to get this error:

1. Required the bundle via Composer and Yarn
2. Required the intl-messageformat via Yarn
3. Added this to my base template
```
<html lang="{{ app.request.locale|split('_')[0] }}">
<script src="{{ url('bazinga_jstranslation_js') }}"></script>
```
4. Added this to my js file
```
import Translator from 'bazinga-translator';
```
5. Used Webpack to build the files

**Comment by stof** [comment]
I think the issue is in https://github.com/willdurand/BazingaJsTranslationBundle/blob/45741f7c6e88a0e5f5e60f5e2c22ddc06b5d1bd3/Resources/js/translator.js#L6-L17
The AMD definition uses `IntlMessageFormat` rather than `intl-messageformat` as module identifier. And as AMD comes before CommonJS, webpack will use the AMD variant rather than the CommonJS one.

**Comment by shtumi** [comment]
so is there any way to run it?

**Comment by carlos-mg89** [comment]
Worked for me: `npm install intl-messageformat --dev`
