### ISSUE TITLE
Doesn't work after upgrading

### ISSUE THREAD

**Issue by 76200** [willdurand/BazingaJsTranslationBundle#84]
After upgrading to `2.0.x-dev`, `bazinga_jstranslation_js` points to `/translations/` ( it doesn't care about default values ) and this route doesn't exist. I have followed the upgrade instructions, removed cache - still without success. Any ideas what might went wrong?

using Symfony 2.4.0

**Comment by smoya** [comment]
Today i had the some error and i didn't found whats the reason yet.

**Comment by smoya** [comment]
Ok, i know whats was the mistake. I use `web` as a dest directory. the problem is that the route path match with the directory `translations`, i mean: 

* Route: /translations
* Directory: web/translations (/translations using web dir as a root)

Could be nice the possibility to change the route path via configuration.
